name: SimpleTranslator # the plugins name as it should appear in the plugin list /pl
version: 1.0 # the plugin's version
author: Deano3663
main: McEssence.SimpleTranslator.Main
api-version: 1.18
commands:
  SimpleTranslator:
    description: SimpleTranslator
    usage: /SimpleTranslator
    permission: SimpleTranslator
  SimpleTranslator reload:
    description: reload plugin
    usage: /SimpleTranslator reload
    permission: SimpleTranslator.admin.reload
  SimpleTranslator myLanguage:
    description: sets player language
    usage: /SimpleTranslator myLanguage
    permission: SimpleTranslator.player.myLanguage
permissions:
  SimpleTranslator.player.*:
    description: Gives access to all SimpleTranslator permissions
    children:
      SimpleTranslator.player.myLanguage: true
  SimpleTranslator.admin.*:
    description: Gives access to all SimpleTranslator admin permissions
    children:
      SimpleTranslator.admin.reload: true
#individual permissions
  SimpleTranslator.player.myLanguage:
    description: Allows you to set your language
    default: op
  SimpleTranslator.admin.reload:
    description: Allows you to reload SimpleTranslator configs
    default: op
